Add available_targets and ambassadors
efatsi/boom_prototype pull request #1
Opened 2021-01-07 21:38 UTC by colorlace

2021-01-07 21:39 UTC, efatsi requested changes

2021-01-07 21:39 UTC, efatsi commented on app/services/available_targets.rb
> +   # Select Hostage: room - self - tackled
looks like you left some shit lying around

2021-01-07 21:47 UTC, colorlace commented on app/services/available_targets.rb
> +   # Select Hostage: room - self - tackled
I done fixed it

2021-01-07 21:47 UTC, efatsi approved these changes
looks real good

2021-01-07 21:49 UTC, efatsi commented on app/services/available_targets.rb
> +      roombutself = room_players.reject{|p| p==from_player}
try
```
room_but_self = room_players - [from_player]
```

2021-01-07 21:50 UTC, efatsi commented on app/services/available_targets.rb
> +        return roombutself.reject{|p| p.is_tackled?}
this could be 
```rb
roombutself.reject(&:tackled?)
```

2021-01-10 14:06 UTC, efatsi commented
Looks like this is already merged, closing PR

2021-01-10 14:06 UTC, closed without merging